### ISSUE TITLE
Create pre-event survey to check attendees' background

### ISSUE THREAD

**Issue by wkwiatek** [nodeschool/wroclaw#14]
Do przygotowania w miarę krótka ankieta, w której uczestnicy odpowiedzą na kilka pytań. Moje propozycje:
- Czy programowałeś wcześniej?
- Jeśli tak, to w jakich językach?
- Czy pracujesz komercyjnie jako programista? 
- Od ilu lat znasz JavaScript? 
- Czy programowałeś wcześniej w NodeJS?
- Czego chciałbyś nauczyć się na NodeSchool? 
- Który z tematów (z http://nodeschool.io/#workshoppers) jest dla Ciebie najbardziej interesujący?

Jeśli macie jakieś pomysły, to śmiało.

**Comment by grabbou** [comment]
Myślę, że super. Można temat podrzucić na nodeschool ogólnie, może inne miasta też zechcą skorzystać. W zasadzie pytania wymieniłeś wszystkie o których wspomnieliśmy, więc mogę przygotować ankietę w Google Docs i wrzucić link do review. Jak będzie wszystko OK, możemy puszczać mailing przez Meetup.
