### ISSUE TITLE
Lightning talks

### ISSUE THREAD

**Issue by grabbou** [nodeschool/wroclaw#3]
Po zakończeniu części "workshopowej" przewidujemy około godzinę na krótkie prezentacje związane z Node.js. Ktoś ma coś ciekawego czym chciałby się podzielić?

Kilka propozycji do wzięcia:
- `babel node` i przykłady użycia ES6 (np. generatorów) w node
- Real-time data processing przy użyciu Event Emitterów 
- How to avoid callback chain (`async`, Promises z np. `bluebird`)
- You tell me

Generalnie wszystkie rzeczy, które przydatne są na początku zabawy z Node.js są mile widziane!

**Comment by grabbou** [comment]
@nodeschool/wroclaw Ktoś coś? W pierwszym momencie planowaliśmy zrobić krótkie prezentacje podsumowujące spotkanie, co wy na to?

**Comment by elkorn** [comment]
Nic nie obiecuję ale jeżeli jutro znajdzie się czas to może przygotuję coś z `babel-node`.

**Comment by grabbou** [comment]
A już mamy niestety o ES6, więc może coś innego? :D
