### ISSUE TITLE
Translate all the things

### ISSUE THREAD

**Issue by grabbou** [nodeschool/wroclaw#5]
Wypadałoby przetłumaczyć / uzupełnić podstawowe Workshopy które mamy w agendzie o język polski. Pracujecie nad czymś już @afronski? Mamy kilku chętnych więc możemy się jakoś logicznie podzielić pracą. Z tego co patrzyłem na nasze agendy, kilka workshopów się zazębia.

**Comment by afronski** [comment]
@grabbou Mieliśmy w planach tłumaczenie `learnyounode` i `javascripting`, ale nie posunęło się to ani trochę do przodu - szczegóły tutaj: https://github.com/nodeschool/silesia/issues/9 - jestem zdecydowanie za podziałem, praca pójdzie efektywniej. :wink:

**Comment by elkorn** [comment]
przejmuję  nodeschool/silesia#9

**Comment by grabbou** [comment]
@afronski możecie łyknąć `javascripting`? Ja przetłumaczę nodeschool.io /mentors-at-events dodane ostatnio. Swoją drogą, jest jakiś kontakt do @nodeschool/lodz? Może checie chłopaki coś przetłumaczyć z nami? :)

**Comment by afronski** [comment]
@grabbou Na pewno nie zdążymy z `javascripting` na 23.05. Co do Łodzi - @adamniedzielski przyzywam Cie. ;)

**Comment by grabbou** [comment]
Wyślemy Wam w prezencie zatem :D

**Comment by adamniedzielski** [comment]
Po pierwszych warsztatach u nas nie było żadnych głosów, że jest problem z brakiem tłumaczeń. Zwrócę na to uwagę podczas kolejnych warsztatów :) Z drugiej strony boję się że aktualizowanie tłumaczeń może być problematyczne.

**Comment by afronski** [comment]
@adamniedzielski @grabbou W przypadku `javascripting` [nie jest to aż tak problematyczne](https://github.com/sethvincent/javascripting/tree/master/i18n) - w zasadzie PR to jeden plik `JSON` i jeden plik `md`. Sytuacja wygląda [analogicznie](https://github.com/workshopper/learnyounode/tree/master/i18n) w `learnyounode`.

**Comment by elkorn** [comment]
@afronski nie do końca - do przetłumaczenia są jeszcze treści zadań i docsy. Zaraz powstawiam co nieco z `learnyounode`. :)

@adamniedzielski podzielam Twoją obawę - problematyczne jest nie tyle samo tłumaczenie co potrzeba śledzenia angielskich repozytoriów w przypadku zmian żeby nadganiać temat.

**Comment by afronski** [comment]
@elkorn Nie wiem o jakich docsach mówisz, ale masz rację z treściami zadań - uprościłem, ale pamiętam o nich. :wink:

@elkorn @adamniedzielski A ja Waszym obaw nie podzielam :wink: - zadania się bardzo rzadko zmieniają, właściwie teraz już w ogóle, więc to jest raczej jednorazowa robota. Poza tym, przygotowaliśmy polskie tłumaczenie strony nodeschool.io około 4-5 miesięcy temu, i od tamtego czasu zmiany były niewielkie - doszła 1 nowa strona i nowe _workshoppery_. A strona zmienia się znacznie bardziej dynamicznie od istniejących warsztatów. 

Powiem tak - najpierw zróbmy, a potem się będziemy martwić. :smile:

**Comment by grabbou** [comment]
Haha, racja @afronski. @adamniedzielski Zdecydowanie bardziej wole się martwić o utrzymanie tego up-to-date niż tłumaczyć ludziom na miejscu na język Polski o co chodzi, gdyż to chyba bardziej problematyczne :)

**Comment by elkorn** [comment]
https://github.com/workshopper/workshopper/pull/110
https://github.com/workshopper/workshopper-exercise/pull/27
https://github.com/workshopper/learnyounode/pull/294

**Comment by grabbou** [comment]
Miejmy nadzieje, że w master poleci przed sobotą:) Super, dzięki!
